Develope
Smart-City-SoSe-2022/Stadtverwaltung pull request #11
Opened 2022-06-11 16:15 UTC by VadimB05

Backend ergänz mit den school api
Frontend angefangen.

2022-06-14 17:28 UTC, lhumke requested changes

2022-06-14 17:28 UTC, lhumke commented on backend/backend/src/main/resources/application.yml
> +    allow-bean-definition-overriding=true:
Wo werden diese Sachen ausgelesen? Ich habe das bei Spring bis jetzt nur mit einer application.properties datei gesehen. Kannst du mit der yml auch Umgebungsvariablen verwenden? Das bräuchte ich, um die Variablen nach dem Compilen noch ändern zu können. Schau dir mal meinen Kommentar bei der Fahrzeugvermietung dazu an

https://github.com/Smart-City-SoSe-2022/Fahrzeugvermietung/pull/11#discussion_r897069357

2022-06-14 17:28 UTC, lhumke commented on backend/backend/pom.xml
> +	</build>
Schau dir mal meinen Kommentar bei der Fahrzeugvermietung an, du hast hier glaube ich das selbe Problem
https://github.com/Smart-City-SoSe-2022/Fahrzeugvermietung/pull/11#discussion_r897073145

2022-06-15 16:17 UTC, VadimB05 commented on backend/backend/src/main/resources/application.yml
> +    allow-bean-definition-overriding=true:
habe es jetzt ergänzt mit den variablen damit du die selbst auch noch verändern kannst.

2022-06-16 13:30 UTC, merged